### ISSUE TITLE
Package Install Python

### ISSUE THREAD

**Issue by reichardtj** [foxglove/nuscenes2bag#1]
Thanks for making this available. This is great. I still have trouble installing all the necessary packages on my windows machine.

All imports run fine after `pip install bagpy` meaning all message definitions etc are available except for the `from foxglove_msgs.msg import ImageMarkerArray` . 

How can I add this so python finds it?

Thanks in advance.

**Comment by jhurliman** [comment]
I'm glad you find it valuable! I developed this with a Docker container so I could move between Mac/Windows/Linux machines without worrying about environment differences between them, but you're more than welcome to try and get it working directly on your machine without a container. The [Dockerfile](https://github.com/foxglove/nuscenes2bag/blob/main/Dockerfile) is going to be the best point of reference. That Python package is installed on Ubuntu/Debian machines with:

```
sudo apt install ros-noetic-foxglove-msgs
```

I realize this is not possible on Windows, though. To be honest, I'm not very familiar with how to install ROS message definitions in Windows so that your Python interpreter can find and import them. The source repository for `ImageMarkerArray` is located at <https://github.com/foxglove/ros_foxglove_msgs> if that is helpful.

**Comment by balajiv18** [comment]
I would like to know whether anybody have worked in anaconda in ubuntu? Thanks

**Comment by jhurliman** [comment]
@balajiv18 I've moved your comment to a discussion post at <https://github.com/foxglove/nuscenes2bag/discussions/7>.

As for the initial issue, I'm going to close it, since running outside the Docker container isn't something we plan to add support for. If anyone does get specific examples working (such as running directly on Windows) a description of how you did it or a PR would be appreciated!
